{% set name = "djangocms-link" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangocms_link-{{ version }}.tar.gz
  sha256: 3e2a8b154d6eae43e5010403f5a0880a98110984b3b36a1de59faf5e3bf7ee0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - django-cms >=3.7,!=4.1,!=4.1.1,!=4.1.2
    - djangocms-attributes-field >=1

test:
  imports:
    - djangocms_link
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Adds a link plugin to django CMS
  home: https://github.com/django-cms/djangocms-link
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
