{% set name = "djangocms-link" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangocms_link-{{ version }}.tar.gz
  sha256: 99a0bc27fe72afb5047ab2092d333ded41bbbaa094e8406bb61351313411bbc3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - django-cms >=3.7,!=4.1,!=4.1.1,!=4.1.2
    - djangocms-attributes-field >=1

test:
  imports:
    - djangocms_link
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Adds a link plugin to django CMS
  home: https://github.com/django-cms/djangocms-link
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
